# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        CÃ¡mara de Comercio
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - /mrBoxieAdminThemePlugin/css/base.css: { media: 'screen, projection, tv' }
    - /mrBoxieAdminThemePlugin/css/themes/<?php echo sfConfig::get("app_boxie_admin_theme"); ?>/styles.css: { media: 'screen, projection, tv' }
    - /mrBoxieAdminThemePlugin/css/ie_7.css: { media: 'screen, projection, tv', condition: 'lte IE 7.0' }
    - /mrBoxieAdminThemePlugin/css/ie_8.css: { media: 'screen, projection, tv', condition: 'IE 8.0' }
    - /css/main.css: { media: 'screen, projection, tv' }
  javascripts:
    - /mrBoxieAdminThemePlugin/js/jquery-1.3.2.min.js
    - /mrBoxieAdminThemePlugin/js/ddpng.js: { condition: 'lte IE 6.0' }
    - /mrBoxieAdminThemePlugin/js/ie.js: { condition: 'lte IE 6.0' }
    - tiny_mce/tiny_mce.js
    - /mrBoxieAdminThemePlugin/js/boxie-admin.js

  has_layout:     true
  layout:         private_layout
