generator:
  class: mrBoxieAdminGenerator
  param:
    model_class:           Client
    theme:                 boxie_admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          client
    with_doctrine_route:   true
    i18n:                  false
    sortable:              false
    actions_base_class:    sfActions
    use_security_yaml_credentials: false

    config:
      actions:  ~
      fields:   ~
      list:
        object_actions:
          edit:
            class: ico edit
            icon: edit.png
          delete:
            class: ico delete
            icon: delete.png
      filter:   ~
      form:     ~
      edit:     ~
      new:      ~
      show:     ~
      export:   ~
